from enum import Enum


class PageActionType(Enum):
    CLICK = "click"
    AUTHENTICATE = "authenticate"
    SET_USER_AGENT = "setUserAgent"
    SCREENSHOT = "screenshot"
    GOTO = "goto"
    GO_BACK = "goBack"
    GO_FORWARD = "goForward"
    EVALUATE = "evaluate"
    SAVE_SNAPSHOT = "saveSnapshot"
    RESTORE_SNAPSHOT = "restoreSnapshot"
    SET_GEOLOCATION = "setGeoLocation"
    CLEAR_GEOLOCATION = "clearGeoLocation"
    SET_VIEWPORT = "setViewport"
    EXTRACT_PAGE_CONTENTS = "extractPageContents"
    EXPOSE_FUNCTION = "exposeFunction"
    REMOVE_FUNCTION = "removeFunction"
    WAIT_FOR_SELECTOR = "waitForSelector"
    # WAIT_FOR_TEXT = "waitForText"
    ADD_SCRIPT_TAG = "addScriptTag"
    REMOVE_SCRIPT_TAG = "removeScriptTag"
    EVALUATE_HANDLE = "evaluateHandle"
    EVALUATE_ON_NEW_DOCUMENT = "evaluateOnNewDocument"
    SET_COOKIE = "setCookie"
    DELETE_COOKIE = "deleteCookie"
    EMULATE_MEDIA = "emulateMedia"
    START_JS_COVERAGE = "startJSCoverage"
    STOP_JS_COVERAGE = "stopJSCoverage"
    GET_PAGE_METRICS = "getPageMetrics"
    GET_ACCESSIBILITY_TREE = "getAccessibilityTree"
    SET_CONTENT = "setContent"
